### PR TITLE
wasm target integration

### PR DESCRIPTION
**Pull request by N7ghtm4r3**
Integrated the `wasm` target integration based on the `JS` [ua-parser](https://github.com/faisalman/ua-parser-js) library.
I have refactored the `DeviceInfoXExt.kt` adding also the `desktop` and the `wasm` targets to execute the related `OnPlatform` and `onPlatform` branch

### CODE REVIEW

**Comment by N7ghtm4r3** [comment]
Hi, any updates about the merge?

**Comment by swapnil-musale** [comment]
@N7ghtm4r3 CI pipeline is broken, can you please check and fix it

**Comment by N7ghtm4r3** [comment]
Can you change the `CI pipeline`? Because the issue was caused due this:
```java 
org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find https://cdn.jsdelivr.net/npm/ua-parser-js:.
Required by:
    project :KDeviceInfo
```
But that is required by the `wasmJs` target here: 
```kotlin
 @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        binaries.executable()
        browser {
            webpackTask {
                dependencies {
                    implementation(libs.x.cdn.jsdelivr.net.npm.ua.parser.js) //here the CI pipeline does not found the package
                }
            }
        }
    }
```

**Comment by N7ghtm4r3** [comment]
Hi, is there any way to bypass that CI pipeline to merge the pull request?

**Comment by swapnil-musale** [comment]
> Hi, is there any way to bypass that CI pipeline to merge the pull request?

Yes, there is option, but if this code get merged then all the future CI pipeline start broke and at the end it will become blocker when we want to publish new lib version through CD.

Can you please make the necessary changes so CI pipeline will start working.

**Comment by N7ghtm4r3** [comment]
Hi, unfortunately that snippet Is mandatory to implement and import the `ua-parser-js` library so must be stay at the moment and I cannot change it

**Comment by swapnil-musale** [comment]
@N7ghtm4r3 I've made the required changes, CI is working fine

Allow me sometime will merge this PR

Thanks for the contribution man 🚀

**Comment by N7ghtm4r3** [comment]
Thank you too!

**Comment by N7ghtm4r3** [comment]
Hi, any updates about the merge?

**Comment by N7ghtm4r3** [comment]
Thank you man!

**Pull request merged**
